# argocd/app-staging.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amrAdel-1/gitops-config
    targetRevision: HEAD
    path: apps/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true