apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
spec:
  selector:
    matchLabels:
      app: gitops-app-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: gitops-app
        image: amradel2002/gitops-app:0f08bc72febe87a7c4406918bf618562cf20853a
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000


